name: Jekyll

on:
  push:
    branches: [ main ]

jobs:
  jekyll:
    runs-on: ubuntu-16.04 # TODO ubuntu-latest
    steps:
    - uses: actions/cache@v2.1.0
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - uses: iranzo/gh-pages-jekyll-action@1.0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        SOURCE_FOLDER: .
    - uses: TheDoctor0/zip-release@0.4.1
